# Generated by Django 4.2 on 2023-05-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customer_address_customuser_address'),
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfood',
            old_name='quantity',
            new_name='food_quantity',
        ),
        migrations.RemoveField(
            model_name='orderedfood',
            name='optional_item',
        ),
        migrations.AddField(
            model_name='deliveryentity',
            name='accept_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryentity',
            name='delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.deliveryperson'),
        ),
        migrations.AddField(
            model_name='deliveryentity',
            name='food_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.foodcart'),
        ),
        migrations.AddField(
            model_name='deliveryentity',
            name='ongoing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryentity',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='food',
            name='optional_items',
            field=models.ManyToManyField(related_name='foods', to='Orders.optionalitem'),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(to='Orders.tag'),
        ),
        migrations.AddField(
            model_name='foodcart',
            name='ordered_food',
            field=models.ManyToManyField(blank=True, to='Orders.orderedfood'),
        ),
        migrations.AddField(
            model_name='foodcart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.AddField(
            model_name='ongoingorder',
            name='delivery_entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.deliveryentity'),
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer'),
        ),
        migrations.CreateModel(
            name='OrderedOptionalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('optional_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.optionalitem')),
                ('ordered_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Orders.orderedfood')),
            ],
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='optional_items',
            field=models.ManyToManyField(through='Orders.OrderedOptionalItem', to='Orders.optionalitem'),
        ),
    ]
