# Generated by Django 4.2 on 2023-05-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_rename_quantity_orderedfood_food_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryentity',
            old_name='accept_order',
            new_name='accept_delivery',
        ),
    ]
