# Generated by Django 4.2 on 2023-05-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_rename_accept_order_deliveryentity_accept_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryentity',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryentity',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='foodcart',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='foodcart',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ongoingorder',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ongoingorder',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderedfood',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderedoptionalitem',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderedoptionalitem',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='date_checked_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderedfood',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
