# Generated by Django 4.2 on 2023-05-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_deliveryentity_created_deliveryentity_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryentity',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='ongoingorder',
            options={'ordering': ['-created']},
        ),
    ]
