# Generated by Django 4.2 on 2023-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0006_rename_ip_address_foodcart_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedfood',
            old_name='ip_address',
            new_name='session_id',
        ),
        migrations.RemoveField(
            model_name='deliveryentity',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='deliveryentity',
            name='session_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
