# Generated by Django 4.2 on 2023-05-16 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_alter_foodcart_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryentity',
            name='food_cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.foodcart'),
        ),
        migrations.RemoveField(
            model_name='foodcart',
            name='ordered_food',
        ),
        migrations.AddField(
            model_name='foodcart',
            name='ordered_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.orderedfood'),
        ),
    ]
