# Generated by Django 4.2 on 2023-05-16 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0009_alter_deliveryentity_food_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryentity',
            name='food_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.foodcart'),
        ),
        migrations.AlterField(
            model_name='deliveryentity',
            name='session_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.RemoveField(
            model_name='foodcart',
            name='ordered_food',
        ),
        migrations.AddField(
            model_name='foodcart',
            name='ordered_food',
            field=models.ManyToManyField(blank=True, to='Orders.orderedfood'),
        ),
    ]
